/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication10;

/**
 *
 * @author user
 */
public class main extends javax.swing.JFrame {

    /** Creates new form main */
    public main() {
        initComponents();
             this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBox14 = new javax.swing.JCheckBox();
        jTextField16 = new javax.swing.JTextField();
        jCheckBox15 = new javax.swing.JCheckBox();
        jTextField17 = new javax.swing.JTextField();
        jCheckBox16 = new javax.swing.JCheckBox();
        jTextField18 = new javax.swing.JTextField();
        jCheckBox17 = new javax.swing.JCheckBox();
        jTextField19 = new javax.swing.JTextField();
        jCheckBox18 = new javax.swing.JCheckBox();
        jTextField20 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salad = new javax.swing.JCheckBox();
        hamburger = new javax.swing.JCheckBox();
        onionrings = new javax.swing.JCheckBox();
        fries = new javax.swing.JCheckBox();
        fishsandwich = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        chickensalad = new javax.swing.JCheckBox();
        cheesesandwich = new javax.swing.JCheckBox();
        chickensandwich = new javax.swing.JCheckBox();
        _fries = new javax.swing.JTextField();
        _salad = new javax.swing.JTextField();
        _hamburger = new javax.swing.JTextField();
        _chickensalad = new javax.swing.JTextField();
        _onionrings = new javax.swing.JTextField();
        _fishsandwich = new javax.swing.JTextField();
        _cheesesandwich = new javax.swing.JTextField();
        _chickensandwich = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hash = new javax.swing.JCheckBox();
        _hash = new javax.swing.JTextField();
        toasted = new javax.swing.JCheckBox();
        _toasted = new javax.swing.JTextField();
        pineapple = new javax.swing.JCheckBox();
        _pineapple = new javax.swing.JTextField();
        chocolate = new javax.swing.JCheckBox();
        _chocolate = new javax.swing.JTextField();
        pancake = new javax.swing.JCheckBox();
        _pancake = new javax.swing.JTextField();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        tea = new javax.swing.JCheckBox();
        _tea = new javax.swing.JTextField();
        cola = new javax.swing.JCheckBox();
        _cola = new javax.swing.JTextField();
        coffee = new javax.swing.JCheckBox();
        _coffee = new javax.swing.JTextField();
        orange = new javax.swing.JCheckBox();
        _orange = new javax.swing.JTextField();
        water = new javax.swing.JCheckBox();
        _water = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _milktea = new javax.swing.JTextField();
        milktea = new javax.swing.JCheckBox();
        royal = new javax.swing.JCheckBox();
        _royal = new javax.swing.JTextField();
        sprite = new javax.swing.JCheckBox();
        _sprite = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jCheckBox14.setText("Fries");

        jCheckBox15.setText("Salad");

        jCheckBox16.setText("Hamburger");

        jCheckBox17.setText("Onion Rings");

        jCheckBox18.setText("Chicken Salad");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gutom na Gutom na Restaurant ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 840, -1));

        salad.setText("Salad ₱65");
        salad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladActionPerformed(evt);
            }
        });
        jPanel1.add(salad, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 188, 93, -1));

        hamburger.setText(" Hamburger ₱39");
        hamburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburgerActionPerformed(evt);
            }
        });
        jPanel1.add(hamburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 230, 120, 30));

        onionrings.setText("Onion Rings ₱18");
        onionrings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onionringsActionPerformed(evt);
            }
        });
        jPanel1.add(onionrings, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 275, -1, -1));

        fries.setText(" Fries  ₱26");
        fries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friesActionPerformed(evt);
            }
        });
        jPanel1.add(fries, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 146, 93, -1));

        fishsandwich.setText("Fish Sandwich  ₱30");
        fishsandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishsandwichActionPerformed(evt);
            }
        });
        jPanel1.add(fishsandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 392, 140, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sandwich");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 355, 237, -1));

        chickensalad.setText("Chicken Salad ₱85");
        chickensalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickensaladActionPerformed(evt);
            }
        });
        jPanel1.add(chickensalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 323, 140, 30));

        cheesesandwich.setText("cheese Sandwich ₱25");
        cheesesandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesesandwichActionPerformed(evt);
            }
        });
        jPanel1.add(cheesesandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 436, 150, -1));

        chickensandwich.setText("Chicken sandwich 35");
        chickensandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickensandwichActionPerformed(evt);
            }
        });
        jPanel1.add(chickensandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 473, -1, -1));

        _fries.setText("0");
        _fries.setEnabled(false);
        jPanel1.add(_fries, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 143, 74, 27));

        _salad.setText("0");
        _salad.setEnabled(false);
        jPanel1.add(_salad, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 185, 74, 27));

        _hamburger.setText("0");
        _hamburger.setEnabled(false);
        jPanel1.add(_hamburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 227, 74, 27));

        _chickensalad.setText("0");
        _chickensalad.setEnabled(false);
        jPanel1.add(_chickensalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 322, 74, 27));

        _onionrings.setText("0");
        _onionrings.setEnabled(false);
        jPanel1.add(_onionrings, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 272, 74, 27));

        _fishsandwich.setText("0");
        _fishsandwich.setEnabled(false);
        jPanel1.add(_fishsandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 74, 27));

        _cheesesandwich.setText("0");
        _cheesesandwich.setEnabled(false);
        jPanel1.add(_cheesesandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 74, 27));

        _chickensandwich.setText("0");
        _chickensandwich.setEnabled(false);
        jPanel1.add(_chickensandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 74, 27));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fast meal Vegetarian ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 107, 237, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Payment Method");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 237, -1));

        hash.setText(" Hash Brown ₱50");
        hash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashActionPerformed(evt);
            }
        });
        jPanel1.add(hash, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 146, 130, -1));

        _hash.setText("0");
        _hash.setEnabled(false);
        jPanel1.add(_hash, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 74, 27));

        toasted.setText("Toasted Bagel ₱55");
        toasted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toastedActionPerformed(evt);
            }
        });
        jPanel1.add(toasted, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 140, 20));

        _toasted.setText("0");
        _toasted.setEnabled(false);
        jPanel1.add(_toasted, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 74, 27));

        pineapple.setText("Pineapple Stick ₱ 45");
        pineapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pineappleActionPerformed(evt);
            }
        });
        jPanel1.add(pineapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 230, 140, -1));

        _pineapple.setText("0");
        _pineapple.setEnabled(false);
        jPanel1.add(_pineapple, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 74, 27));

        chocolate.setText("chocolate Muffin ₱ 80");
        chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateActionPerformed(evt);
            }
        });
        jPanel1.add(chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 275, -1, -1));

        _chocolate.setText("0");
        _chocolate.setEnabled(false);
        jPanel1.add(_chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 74, 27));

        pancake.setText("Pancake syrup ₱40");
        pancake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pancakeActionPerformed(evt);
            }
        });
        jPanel1.add(pancake, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 323, 140, -1));

        _pancake.setText("0");
        _pancake.setEnabled(false);
        jPanel1.add(_pancake, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 74, 27));

        jCheckBox19.setText("Fries");
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 146, 93, -1));

        jCheckBox21.setText("Hamburger");
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 230, 93, -1));

        jCheckBox22.setText("Onion Rings");
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 275, -1, -1));

        jCheckBox23.setText("Chicken Salad");
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 323, 113, -1));

        tea.setText("Tea ₱35");
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });
        jPanel1.add(tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 93, -1));

        _tea.setText("0");
        _tea.setEnabled(false);
        jPanel1.add(_tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 74, 27));

        cola.setText("Cola ₱35");
        cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaActionPerformed(evt);
            }
        });
        jPanel1.add(cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 93, -1));

        _cola.setText("0");
        _cola.setEnabled(false);
        jPanel1.add(_cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 74, 27));

        coffee.setText("Coffee ₱40");
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });
        jPanel1.add(coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 93, -1));

        _coffee.setText("0");
        _coffee.setEnabled(false);
        jPanel1.add(_coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 74, 27));

        orange.setText("Orange ₱50");
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });
        jPanel1.add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        _orange.setText("0");
        _orange.setEnabled(false);
        jPanel1.add(_orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 74, 27));

        water.setText("Water ₱30");
        water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterActionPerformed(evt);
            }
        });
        jPanel1.add(water, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 113, -1));

        _water.setText("0");
        _water.setEnabled(false);
        jPanel1.add(_water, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 74, 27));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Drinks");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 237, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Drinks");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 237, -1));

        _milktea.setText("0");
        _milktea.setEnabled(false);
        jPanel1.add(_milktea, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 74, 27));

        milktea.setText("MilkTea ₱45");
        milktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkteaActionPerformed(evt);
            }
        });
        jPanel1.add(milktea, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 113, -1));

        royal.setText("Royal ₱30");
        royal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                royalActionPerformed(evt);
            }
        });
        jPanel1.add(royal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        _royal.setText("0");
        _royal.setEnabled(false);
        jPanel1.add(_royal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 74, 27));

        sprite.setText(" Sprite ₱30");
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });
        jPanel1.add(sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 93, -1));

        _sprite.setText("0");
        _sprite.setEnabled(false);
        jPanel1.add(_sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 74, 27));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fast meal Vegetarian ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 237, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total Cost:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 20));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 120, -1));

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 90, 30));

        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 90, 30));

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 90, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Change");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, 20));
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 120, -1));
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Amount");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 842, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void friesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friesActionPerformed
       if(fries.isSelected())
       {
           _fries.setEnabled(true);
       }
       else
           _fries.setEnabled(false);
       _fries.setText("0");
    }//GEN-LAST:event_friesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      double[] itemcost = new double[22];
      double totals;
        itemcost[0]= Double.parseDouble(_fries.getText());
       itemcost[1]= Double.parseDouble(_salad.getText());
       itemcost[2]= Double.parseDouble(_hamburger.getText());
       itemcost[3]= Double.parseDouble(_onionrings.getText());
       itemcost[4]= Double.parseDouble(_chickensalad.getText());
        itemcost[5]= Double.parseDouble(_fishsandwich.getText());
       itemcost[6]= Double.parseDouble(_cheesesandwich.getText());
       itemcost[7]= Double.parseDouble(_chickensandwich.getText());
       
       itemcost[8]= Double.parseDouble(_hash.getText());
       itemcost[9]= Double.parseDouble(_toasted.getText());
        itemcost[10]= Double.parseDouble(_pineapple.getText());
       itemcost[11]= Double.parseDouble(_chocolate.getText());
       itemcost[12]= Double.parseDouble(_pancake.getText());
       
       itemcost[13]= Double.parseDouble(_tea.getText());
       itemcost[14]= Double.parseDouble(_cola.getText());
       itemcost[15]= Double.parseDouble(_coffee.getText());
       itemcost[16]= Double.parseDouble(_orange.getText());
       itemcost[17]= Double.parseDouble(_water.getText());
       
       itemcost[18]= Double.parseDouble(_sprite.getText());
       itemcost[19]= Double.parseDouble(_royal.getText());
       itemcost[20]= Double.parseDouble(_milktea.getText());
       
       
      totals =  (itemcost[0] *26)+ (itemcost[1] *65)+ (itemcost[2] *39)+ (itemcost[3] *18)+ (itemcost[4] *85)+(itemcost[5] *30)+ (itemcost[6] *25)+(itemcost[7] *35)+(itemcost[8] *50)+(itemcost[9] *55)+(itemcost[10] *45) +(itemcost[11] *80)+(itemcost[12] *40)+(itemcost[13] *35)+(itemcost[14] *35)+(itemcost[15] *40)+(itemcost[16] *50)+(itemcost[17] *30)+(itemcost[18] *30)+(itemcost[19] *30)+(itemcost[20] *45);
              ;
      total.setText(Double.toString(totals));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladActionPerformed
       if(salad.isSelected())
       {
           _salad.setEnabled(true);
       }
       else
           _salad.setEnabled(false);
       _salad.setText("0");
    }//GEN-LAST:event_saladActionPerformed

    private void hamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburgerActionPerformed
               if(hamburger.isSelected())
       {
           _hamburger.setEnabled(true);
           
       }
       else
           _hamburger.setEnabled(false);
               _hamburger.setText("0");
    }//GEN-LAST:event_hamburgerActionPerformed

    private void onionringsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onionringsActionPerformed
              if(onionrings.isSelected())
       {
           _onionrings.setEnabled(true);
       }
       else
           _onionrings.setEnabled(false);
              _onionrings.setText("0");
    }//GEN-LAST:event_onionringsActionPerformed

    private void chickensaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickensaladActionPerformed
            if(chickensalad.isSelected())
       {
           _chickensalad.setEnabled(true);
       }
       else
           _chickensalad.setEnabled(false);
            _chickensalad.setText("0");
    }//GEN-LAST:event_chickensaladActionPerformed

    private void fishsandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishsandwichActionPerformed
             if(fishsandwich.isSelected())
       {
           _fishsandwich.setEnabled(true);
       }
       else
           _fishsandwich.setEnabled(false);
             _fishsandwich.setText("0");
    }//GEN-LAST:event_fishsandwichActionPerformed

    private void cheesesandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheesesandwichActionPerformed
               if(cheesesandwich.isSelected())
       {
           _cheesesandwich.setEnabled(true);
       }
       else
           _cheesesandwich.setEnabled(false);
               _cheesesandwich.setText("0");
    }//GEN-LAST:event_cheesesandwichActionPerformed

    private void chickensandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickensandwichActionPerformed
               if(chickensandwich.isSelected())
       {
           _chickensandwich.setEnabled(true);
       }
       else
           _chickensandwich.setEnabled(false);
               _chickensandwich.setText("0");
    }//GEN-LAST:event_chickensandwichActionPerformed

    private void hashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashActionPerformed
         if(hash.isSelected())
       {
           _hash.setEnabled(true);
       }
       else
           _hash.setEnabled(false);
         _hash.setText("0");
    }//GEN-LAST:event_hashActionPerformed

    private void toastedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toastedActionPerformed
          if(toasted.isSelected())
       {
           _toasted.setEnabled(true);
       }
       else
           _toasted.setEnabled(false);
          _toasted.setText("0");
    }//GEN-LAST:event_toastedActionPerformed

    private void pineappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pineappleActionPerformed
         if(pineapple.isSelected())
       {
           _pineapple.setEnabled(true);
       }
       else
           _pineapple.setEnabled(false);
         _pineapple.setText("0");
    }//GEN-LAST:event_pineappleActionPerformed

    private void chocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateActionPerformed
         if(chocolate.isSelected())
       {
           _chocolate.setEnabled(true);
       }
       else
           _chocolate.setEnabled(false);
         _chocolate.setText("0");
    }//GEN-LAST:event_chocolateActionPerformed

    private void pancakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pancakeActionPerformed
        if(pancake.isSelected())
       {
           _pancake.setEnabled(true);
       }
       else
           _pancake.setEnabled(false);
        _pancake.setText("0");
    }//GEN-LAST:event_pancakeActionPerformed

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
         if(tea.isSelected())
       {
           _tea.setEnabled(true);
       }
       else
           _tea.setEnabled(false);
         _tea.setText("0");
    }//GEN-LAST:event_teaActionPerformed

    private void colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaActionPerformed
        if(cola.isSelected())
       {
           _cola.setEnabled(true);
       }
       else
           _cola.setEnabled(false);
        _cola.setText("0");
    }//GEN-LAST:event_colaActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
         if(coffee.isSelected())
       {
           _coffee.setEnabled(true);
       }
       else
           _coffee.setEnabled(false);
         _coffee.setText("0");
    }//GEN-LAST:event_coffeeActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
         if(orange.isSelected())
       {
           _orange.setEnabled(true);
       }
       else
           _orange.setEnabled(false);
         _orange.setText("0");
    }//GEN-LAST:event_orangeActionPerformed

    private void waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterActionPerformed
         if(water.isSelected())
       {
           _water.setEnabled(true);
       }
       else
           _water.setEnabled(false);
         _water.setText("0");
    }//GEN-LAST:event_waterActionPerformed

    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
                if(sprite.isSelected())
       {
           _sprite.setEnabled(true);
       }
       else
           _sprite.setEnabled(false);
                _sprite.setText("0");
    }//GEN-LAST:event_spriteActionPerformed

    private void royalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_royalActionPerformed
                  if(royal.isSelected())
       {
           _royal.setEnabled(true);
       }
       else
           _royal.setEnabled(false);
                  _royal.setText("0");
    }//GEN-LAST:event_royalActionPerformed

    private void milkteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkteaActionPerformed
                   if(milktea.isSelected())
       {
           _milktea.setEnabled(true);
       }
       else
           _milktea.setEnabled(false);
                   _milktea.setText("0");
    }//GEN-LAST:event_milkteaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double changes =   Double.parseDouble(amount.getText()) -Double.parseDouble(total.getText());
        change.setText(Double.toString(changes));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            fries.setSelected(false);
            salad.setSelected(false);
            hamburger.setSelected(false);
            onionrings.setSelected(false);
            chickensalad.setSelected(false);
            
             fishsandwich.setSelected(false);
            cheesesandwich.setSelected(false);
            chickensandwich.setSelected(false);
            
            hash.setSelected(false);
            toasted.setSelected(false);
             pineapple.setSelected(false);
            chocolate.setSelected(false);
            pancake.setSelected(false);
            
            tea.setSelected(false);
            cola.setSelected(false);
            coffee.setSelected(false);
            
             orange.setSelected(false);
            water.setSelected(false);
            sprite.setSelected(false);
            royal.setSelected(false);
            milktea.setSelected(false);
            
             _fries.setText("0");
              _hamburger.setText("0");
               _salad.setText("0");
                _onionrings.setText("0");
                 _chickensalad.setText("0");
                  _fishsandwich.setText("0");
                   _cheesesandwich.setText("0");
                    _chickensandwich.setText("0");
                     _hash.setText("0");
                      _toasted.setText("0");
                       _chocolate.setText("0");
                       _pineapple.setText("0");
                       _pancake.setText("0");
                       _tea.setText("0");
                       _cola.setText("0");
                       _coffee.setText("0");
                       _orange.setText("0");
                       _water.setText("0");
                       
                       _sprite.setText("0");
                       _royal.setText("0");
                       _milktea.setText("0");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _cheesesandwich;
    private javax.swing.JTextField _chickensalad;
    private javax.swing.JTextField _chickensandwich;
    private javax.swing.JTextField _chocolate;
    private javax.swing.JTextField _coffee;
    private javax.swing.JTextField _cola;
    private javax.swing.JTextField _fishsandwich;
    private javax.swing.JTextField _fries;
    private javax.swing.JTextField _hamburger;
    private javax.swing.JTextField _hash;
    private javax.swing.JTextField _milktea;
    private javax.swing.JTextField _onionrings;
    private javax.swing.JTextField _orange;
    private javax.swing.JTextField _pancake;
    private javax.swing.JTextField _pineapple;
    private javax.swing.JTextField _royal;
    private javax.swing.JTextField _salad;
    private javax.swing.JTextField _sprite;
    private javax.swing.JTextField _tea;
    private javax.swing.JTextField _toasted;
    private javax.swing.JTextField _water;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField change;
    private javax.swing.JCheckBox cheesesandwich;
    private javax.swing.JCheckBox chickensalad;
    private javax.swing.JCheckBox chickensandwich;
    private javax.swing.JCheckBox chocolate;
    private javax.swing.JCheckBox coffee;
    private javax.swing.JCheckBox cola;
    private javax.swing.JCheckBox fishsandwich;
    private javax.swing.JCheckBox fries;
    private javax.swing.JCheckBox hamburger;
    private javax.swing.JCheckBox hash;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JCheckBox milktea;
    private javax.swing.JCheckBox onionrings;
    private javax.swing.JCheckBox orange;
    private javax.swing.JCheckBox pancake;
    private javax.swing.JCheckBox pineapple;
    private javax.swing.JCheckBox royal;
    private javax.swing.JCheckBox salad;
    private javax.swing.JCheckBox sprite;
    private javax.swing.JCheckBox tea;
    private javax.swing.JCheckBox toasted;
    private javax.swing.JTextField total;
    private javax.swing.JCheckBox water;
    // End of variables declaration//GEN-END:variables

}
